### ISSUE TITLE
hi ？ are you coding finsh？

### ISSUE THREAD

**Issue by sjyttkl** [maidacundo/MoE-LoRA#1]
hi ？ are you coding finsh？

**Comment by maidacundo** [comment]
i am still working on the training experiments. At the moment it is possible to launch a training on wikipedia-it, but it was run purely to test the proposed method. I will add more soon.

**Comment by sjyttkl** [comment]
Based on these experiments, will you publish a paper?

**Comment by maidacundo** [comment]
i dont think so, just doing for fun :)
